/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SearchRouteImport } from './routes/search'
import { Route as RecentRouteImport } from './routes/recent'
import { Route as QueueRouteImport } from './routes/queue'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as PlaylistsRouteImport } from './routes/playlists'
import { Route as LyricsRouteImport } from './routes/lyrics'
import { Route as LikedRouteImport } from './routes/liked'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as GetAppRouteImport } from './routes/get-app'
import { Route as EqualizerRouteImport } from './routes/equalizer'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PlaylistsIdRouteImport } from './routes/playlists.$id'
import { Route as ApiPublicYoutubeAudioRouteImport } from './routes/api/public/youtube-audio'
import { Route as ApiPublicProxyRouteImport } from './routes/api/public/proxy'

const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const RecentRoute = RecentRouteImport.update({
  id: '/recent',
  path: '/recent',
  getParentRoute: () => rootRouteImport,
} as any)
const QueueRoute = QueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsRoute = PlaylistsRouteImport.update({
  id: '/playlists',
  path: '/playlists',
  getParentRoute: () => rootRouteImport,
} as any)
const LyricsRoute = LyricsRouteImport.update({
  id: '/lyrics',
  path: '/lyrics',
  getParentRoute: () => rootRouteImport,
} as any)
const LikedRoute = LikedRouteImport.update({
  id: '/liked',
  path: '/liked',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const GetAppRoute = GetAppRouteImport.update({
  id: '/get-app',
  path: '/get-app',
  getParentRoute: () => rootRouteImport,
} as any)
const EqualizerRoute = EqualizerRouteImport.update({
  id: '/equalizer',
  path: '/equalizer',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PlaylistsIdRoute = PlaylistsIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => PlaylistsRoute,
} as any)
const ApiPublicYoutubeAudioRoute = ApiPublicYoutubeAudioRouteImport.update({
  id: '/api/public/youtube-audio',
  path: '/api/public/youtube-audio',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicProxyRoute = ApiPublicProxyRouteImport.update({
  id: '/api/public/proxy',
  path: '/api/public/proxy',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/equalizer': typeof EqualizerRoute
  '/get-app': typeof GetAppRoute
  '/library': typeof LibraryRoute
  '/liked': typeof LikedRoute
  '/lyrics': typeof LyricsRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/youtube-audio': typeof ApiPublicYoutubeAudioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/equalizer': typeof EqualizerRoute
  '/get-app': typeof GetAppRoute
  '/library': typeof LibraryRoute
  '/liked': typeof LikedRoute
  '/lyrics': typeof LyricsRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/youtube-audio': typeof ApiPublicYoutubeAudioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/downloads': typeof DownloadsRoute
  '/equalizer': typeof EqualizerRoute
  '/get-app': typeof GetAppRoute
  '/library': typeof LibraryRoute
  '/liked': typeof LikedRoute
  '/lyrics': typeof LyricsRoute
  '/playlists': typeof PlaylistsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/queue': typeof QueueRoute
  '/recent': typeof RecentRoute
  '/search': typeof SearchRoute
  '/settings': typeof SettingsRoute
  '/playlists/$id': typeof PlaylistsIdRoute
  '/api/public/proxy': typeof ApiPublicProxyRoute
  '/api/public/youtube-audio': typeof ApiPublicYoutubeAudioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/downloads'
    | '/equalizer'
    | '/get-app'
    | '/library'
    | '/liked'
    | '/lyrics'
    | '/playlists'
    | '/profile'
    | '/queue'
    | '/recent'
    | '/search'
    | '/settings'
    | '/playlists/$id'
    | '/api/public/proxy'
    | '/api/public/youtube-audio'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/downloads'
    | '/equalizer'
    | '/get-app'
    | '/library'
    | '/liked'
    | '/lyrics'
    | '/playlists'
    | '/profile'
    | '/queue'
    | '/recent'
    | '/search'
    | '/settings'
    | '/playlists/$id'
    | '/api/public/proxy'
    | '/api/public/youtube-audio'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/downloads'
    | '/equalizer'
    | '/get-app'
    | '/library'
    | '/liked'
    | '/lyrics'
    | '/playlists'
    | '/profile'
    | '/queue'
    | '/recent'
    | '/search'
    | '/settings'
    | '/playlists/$id'
    | '/api/public/proxy'
    | '/api/public/youtube-audio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  DownloadsRoute: typeof DownloadsRoute
  EqualizerRoute: typeof EqualizerRoute
  GetAppRoute: typeof GetAppRoute
  LibraryRoute: typeof LibraryRoute
  LikedRoute: typeof LikedRoute
  LyricsRoute: typeof LyricsRoute
  PlaylistsRoute: typeof PlaylistsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  QueueRoute: typeof QueueRoute
  RecentRoute: typeof RecentRoute
  SearchRoute: typeof SearchRoute
  SettingsRoute: typeof SettingsRoute
  ApiPublicProxyRoute: typeof ApiPublicProxyRoute
  ApiPublicYoutubeAudioRoute: typeof ApiPublicYoutubeAudioRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recent': {
      id: '/recent'
      path: '/recent'
      fullPath: '/recent'
      preLoaderRoute: typeof RecentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/queue': {
      id: '/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof QueueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists': {
      id: '/playlists'
      path: '/playlists'
      fullPath: '/playlists'
      preLoaderRoute: typeof PlaylistsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lyrics': {
      id: '/lyrics'
      path: '/lyrics'
      fullPath: '/lyrics'
      preLoaderRoute: typeof LyricsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/liked': {
      id: '/liked'
      path: '/liked'
      fullPath: '/liked'
      preLoaderRoute: typeof LikedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-app': {
      id: '/get-app'
      path: '/get-app'
      fullPath: '/get-app'
      preLoaderRoute: typeof GetAppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equalizer': {
      id: '/equalizer'
      path: '/equalizer'
      fullPath: '/equalizer'
      preLoaderRoute: typeof EqualizerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/playlists/$id': {
      id: '/playlists/$id'
      path: '/$id'
      fullPath: '/playlists/$id'
      preLoaderRoute: typeof PlaylistsIdRouteImport
      parentRoute: typeof PlaylistsRoute
    }
    '/api/public/youtube-audio': {
      id: '/api/public/youtube-audio'
      path: '/api/public/youtube-audio'
      fullPath: '/api/public/youtube-audio'
      preLoaderRoute: typeof ApiPublicYoutubeAudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/proxy': {
      id: '/api/public/proxy'
      path: '/api/public/proxy'
      fullPath: '/api/public/proxy'
      preLoaderRoute: typeof ApiPublicProxyRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PlaylistsRouteChildren {
  PlaylistsIdRoute: typeof PlaylistsIdRoute
}

const PlaylistsRouteChildren: PlaylistsRouteChildren = {
  PlaylistsIdRoute: PlaylistsIdRoute,
}

const PlaylistsRouteWithChildren = PlaylistsRoute._addFileChildren(
  PlaylistsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  DownloadsRoute: DownloadsRoute,
  EqualizerRoute: EqualizerRoute,
  GetAppRoute: GetAppRoute,
  LibraryRoute: LibraryRoute,
  LikedRoute: LikedRoute,
  LyricsRoute: LyricsRoute,
  PlaylistsRoute: PlaylistsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  QueueRoute: QueueRoute,
  RecentRoute: RecentRoute,
  SearchRoute: SearchRoute,
  SettingsRoute: SettingsRoute,
  ApiPublicProxyRoute: ApiPublicProxyRoute,
  ApiPublicYoutubeAudioRoute: ApiPublicYoutubeAudioRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
